### ISSUE TITLE
Session storage loses state

### ISSUE THREAD

**Issue by ThomasBleijendaal** [ITfoxtec/ITfoxtec.Identity.BlazorWebAssembly.OpenidConnect#4]
I was testing this package, and got it working with Azure AD and with another OpenID Connect provider, but noticed an exception in the debug log of my WebAssembly application:

```Unhandled exception rendering component: Failed to handle login call back, response URL 'https://localhost:5001/authentication/login_callback#code={code}&state=w_ioLy2BM3RPMk4jw_GDL0hPhHQuKzAQ1lYOdIiccKw&session_state=dc368464-662b-4ca2-b014-cccfe736de31'.
System.Security.SecurityException: Failed to handle login call back, response URL 'https://localhost:5001/authentication/login_callback#code={code}&state=w_ioLy2BM3RPMk4jw_GDL0hPhHQuKzAQ1lYOdIiccKw&session_state=dc368464-662b-4ca2-b014-cccfe736de31'.
 ---> System.Security.SecurityException: State 'w_ioLy2BM3RPMk4jw_GDL0hPhHQuKzAQ1lYOdIiccKw' do not exist.
   at ITfoxtec.Identity.BlazorWebAssembly.OpenidConnect.OpenidConnectPkce.LoginCallBackAsync(String responseUrl)
   --- End of inner exception stack trace ---
   at ITfoxtec.Identity.BlazorWebAssembly.OpenidConnect.OpenidConnectPkce.LoginCallBackAsync(String responseUrl)
   at ITfoxtec.Identity.BlazorWebAssembly.OpenidConnect.AuthenticationPageBase.OnInitializedAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)```

It looks like the session storage item that is used to store the state gets cleared, or the component gets triggered twice. The user session is stored correctly in the session storage, so the authentication works correctly.

**Comment by Revsgaard** [comment]
Thank you for the contribution. The error is resolved in https://github.com/ITfoxtec/ITfoxtec.Identity.BlazorWebAssembly.OpenidConnect/commit/ff57eb311bbe9a2e8c9155253763a82adab3de45
